name: ai_translate
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  get: ^4.7.2
  http: ^1.3.0
  shared_preferences: ^2.5.3
  toastification: ^3.0.2
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
